# Generated by Django 5.0.6 on 2025-05-12 01:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=45, unique=True)),
                ('cargo', models.CharField(max_length=80)),
                ('fecha_ingreso', models.DateField()),
                ('departamento', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=45)),
                ('estado_civil', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('obligatorio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoLaboral',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('url_resolucion_evento', models.CharField(max_length=500)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.perfilfuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.perfilfuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioFuncionario',
            fields=[
                ('id_beneficio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_beneficio', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
<<<<<<< HEAD
                ('url_archivo', models.CharField(max_length=500)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.perfilfuncionario')),
=======
                ('url_resolucion_beneficios', models.FileField(
                    blank=True,
                    null=True,
                    upload_to='beneficios/',
                    validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]
             )),('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.perfilfuncionario')),
>>>>>>> branch-RossNuevo
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_presentacion', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'doc', 'docx'])])),
                ('estado', models.CharField(max_length=45)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.perfilfuncionario')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.tipodocumento')),
            ],
        ),
    ]
