# Generated by Django 5.2 on 2025-05-17 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tthh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventolaboral',
            name='url_resolucion_evento',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
    ]
