# Generated by Django 5.2 on 2025-05-18 00:09

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tthh', '0002_alter_eventolaboral_url_resolucion_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiofuncionario',
            name='url_resolucion_beneficios',
            field=models.FileField(
                upload_to='beneficios/',
                blank=True,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])
                ]
            ),
        ),
    ]
