# Generated by Django 4.2.4 on 2025-05-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('obligatorio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EventoLaboral',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('url_resolucion_evento', models.CharField(max_length=500)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.perfilfuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.perfilfuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_presentacion', models.DateField()),
                ('url_archivo', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=45)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.perfilfuncionario')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioFuncionario',
            fields=[
                ('id_beneficio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_beneficio', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('url_archivo', models.CharField(max_length=500)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.perfilfuncionario')),
            ],
        ),
    ]
