# Generated by Django 4.2.4 on 2025-05-05 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tipodocumento_usuario_perfilusuario_eventolaboral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentofuncionario',
            name='url_archivo',
        ),
        migrations.AddField(
            model_name='documentofuncionario',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'doc', 'docx'])]),
        ),
    ]
